# Generated by Django 6.1 on 2026-09-03 08:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proforma_number', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('client_address', models.CharField(blank=True, max_length=255)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('purpose', models.CharField(blank=True, help_text="What this proforma is for, e.g. 'Solar lights and CCTV installation'.", max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='Percentage, e.g. 18.00 for 18%.', max_digits=5)),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_costs_description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('converted', 'Converted to Invoice')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proforma.proforma')),
            ],
        ),
    ]
