# Generated by Django 6.1 on 2026-08-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('specification', models.CharField(blank=True, max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('own_stock', 'Own Stock'), ('supplier', 'External Supplier')], max_length=20)),
            ],
        ),
    ]
