# Generated by Django 6.1 on 2026-08-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_unit_price_product_selling_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='minimum_selling_price',
        ),
    ]
