# Generated by Django 6.1 on 2026-08-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_selling_price_product_minimum_selling_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('item_name', 'brand', 'specification'), name='unique_product_brand_specification'),
        ),
    ]
