# Generated by Django 6.1 on 2026-08-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank'), ('card', 'Card'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('credit', 'Credit')], default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
